//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public int idBill { get; set; }
        public int idCustom { get; set; }
        public int idUserNV { get; set; }
        public int idBuild { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string content { get; set; }
        public string cmndTruoc { get; set; }
        public string cmndSau { get; set; }
        public Nullable<System.DateTime> ngayKyTen { get; set; }
        public string kyten { get; set; }
    
        public virtual BUILDING BUILDING { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual USER USER { get; set; }
    }
}
