//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUILDING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUILDING()
        {
            this.BILLs = new HashSet<BILL>();
            this.PHIEUHENs = new HashSet<PHIEUHEN>();
            this.IMAGEs = new HashSet<IMAGE>();
            this.SERVICES = new HashSet<SERVICE>();
        }
    
        public int idBuild { get; set; }
        public int idWard { get; set; }
        public int idUser { get; set; }
        public int idType { get; set; }
        public string nameBuild { get; set; }
        public string street { get; set; }
        public Nullable<decimal> floorarea { get; set; }
        public Nullable<int> floor { get; set; }
        public string conent { get; set; }
        public Nullable<decimal> price { get; set; }
        public string depositDate { get; set; }
        public string nameManager { get; set; }
        public string phoneManager { get; set; }
        public Nullable<int> idHuong { get; set; }
        public Nullable<int> idStatus { get; set; }
        public string deposits { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual TYPE TYPE { get; set; }
        public virtual USER USER { get; set; }
        public virtual WARD WARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUHEN> PHIEUHENs { get; set; }
        public virtual HUONG HUONG { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGE> IMAGEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE> SERVICES { get; set; }
    }
}
