//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public int idNews { get; set; }
        public int idUser { get; set; }
        public string titleNews { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string Img { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
