//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatDongSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUHEN
    {
        public int idPhieu { get; set; }
        public int idCustom { get; set; }
        public int idUserNV { get; set; }
        public int idBuild { get; set; }
        public string contentPhieu { get; set; }
        public Nullable<System.DateTime> createPhieu { get; set; }
        public Nullable<System.DateTime> ngayhen { get; set; }
    
        public virtual BUILDING BUILDING { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual USER USER { get; set; }
    }
}
